version: 2

project_name: rlcs-cli

before:
  hooks:
    - go mod tidy

builds:
  - id: rlcs-cli
    main: ./cmd/rlcs-cli
    binary: rlcs-cli
    ldflags:
      - -s -w -X main.version={{.Version}}
    targets:
      - darwin_amd64
      - darwin_arm64
      - linux_amd64
      - linux_arm64
      - windows_amd64
      - windows_arm64

archives:
  - formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - README.md

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - Merge pull request
      - Merge branch

release:
  github:
    owner: mgranderath
    name: rlcs-cli
  draft: false
  prerelease: auto

checksum:
  name_template: 'checksums.txt'

brews:
  - name: rlcs-cli
    repository:
      owner: mgranderath
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    directory: Formula
    homepage: "https://github.com/mgranderath/rlcs-cli"
    description: "CLI tool for RLCS (Rocket League Championship Series)"
    license: "MIT"
    dependencies:
      - name: git
    test: |
      system "#{bin}/rlcs-cli", "--version"
    install: |
      bin.install "rlcs-cli"
